# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cycles_api import CyclesApi  # noqa: E501


class TestCyclesApi(unittest.TestCase):
    """CyclesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CyclesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_batch_create_cycles_data_sci_mdas_v1_cycles_batch_post(self) -> None:
        """Test case for batch_create_cycles_data_sci_mdas_v1_cycles_batch_post

        Batch Create Cycles  # noqa: E501
        """
        pass

    def test_create_cycle_data_sci_mdas_v1_cycles_post(self) -> None:
        """Test case for create_cycle_data_sci_mdas_v1_cycles_post

        Create Cycle  # noqa: E501
        """
        pass

    def test_create_cycle_data_sci_mdas_v2_cycles_post(self) -> None:
        """Test case for create_cycle_data_sci_mdas_v2_cycles_post

        Create Cycle  # noqa: E501
        """
        pass

    def test_delete_cycle_data_sci_mdas_v1_cycles_cycle_id_delete(self) -> None:
        """Test case for delete_cycle_data_sci_mdas_v1_cycles_cycle_id_delete

        Delete Cycle  # noqa: E501
        """
        pass

    def test_delete_cycle_data_sci_mdas_v2_cycles_cycle_id_delete(self) -> None:
        """Test case for delete_cycle_data_sci_mdas_v2_cycles_cycle_id_delete

        Delete Cycle  # noqa: E501
        """
        pass

    def test_get_cycles_in_range_for_user_data_sci_mdas_v1_cycles_get(self) -> None:
        """Test case for get_cycles_in_range_for_user_data_sci_mdas_v1_cycles_get

        Get Cycles In Range For User  # noqa: E501
        """
        pass

    def test_get_cycles_in_range_for_user_data_sci_mdas_v2_cycles_get(self) -> None:
        """Test case for get_cycles_in_range_for_user_data_sci_mdas_v2_cycles_get

        Get Cycles In Range For User  # noqa: E501
        """
        pass

    def test_update_cycle_data_sci_mdas_v1_cycles_cycle_id_put(self) -> None:
        """Test case for update_cycle_data_sci_mdas_v1_cycles_cycle_id_put

        Update Cycle  # noqa: E501
        """
        pass

    def test_update_cycle_data_sci_mdas_v2_cycles_cycle_id_put(self) -> None:
        """Test case for update_cycle_data_sci_mdas_v2_cycles_cycle_id_put

        Update Cycle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
