# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.recoveries_api import RecoveriesApi  # noqa: E501


class TestRecoveriesApi(unittest.TestCase):
    """RecoveriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecoveriesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_batch_create_recoveries_data_sci_mdas_v1_recoveries_batch_post(self) -> None:
        """Test case for batch_create_recoveries_data_sci_mdas_v1_recoveries_batch_post

        Batch Create Recoveries  # noqa: E501
        """
        pass

    def test_create_recovery_data_sci_mdas_v1_recoveries_post(self) -> None:
        """Test case for create_recovery_data_sci_mdas_v1_recoveries_post

        Create Recovery  # noqa: E501
        """
        pass

    def test_create_recovery_data_sci_mdas_v2_recoveries_post(self) -> None:
        """Test case for create_recovery_data_sci_mdas_v2_recoveries_post

        Create Recovery  # noqa: E501
        """
        pass

    def test_delete_recovery_data_sci_mdas_v1_recoveries_recovery_id_delete(self) -> None:
        """Test case for delete_recovery_data_sci_mdas_v1_recoveries_recovery_id_delete

        Delete Recovery  # noqa: E501
        """
        pass

    def test_delete_recovery_data_sci_mdas_v2_recoveries_recovery_id_delete(self) -> None:
        """Test case for delete_recovery_data_sci_mdas_v2_recoveries_recovery_id_delete

        Delete Recovery  # noqa: E501
        """
        pass

    def test_get_recoveries_in_range_for_user_data_sci_mdas_v1_recoveries_get(self) -> None:
        """Test case for get_recoveries_in_range_for_user_data_sci_mdas_v1_recoveries_get

        Get Recoveries In Range For User  # noqa: E501
        """
        pass

    def test_get_recoveries_in_range_for_user_data_sci_mdas_v2_recoveries_get(self) -> None:
        """Test case for get_recoveries_in_range_for_user_data_sci_mdas_v2_recoveries_get

        Get Recoveries In Range For User  # noqa: E501
        """
        pass

    def test_update_recovery_data_sci_mdas_v1_recoveries_recovery_id_put(self) -> None:
        """Test case for update_recovery_data_sci_mdas_v1_recoveries_recovery_id_put

        Update Recovery  # noqa: E501
        """
        pass

    def test_update_recovery_data_sci_mdas_v2_recoveries_recovery_id_put(self) -> None:
        """Test case for update_recovery_data_sci_mdas_v2_recoveries_recovery_id_put

        Update Recovery  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
