# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.date_range import DateRange  # noqa: E501

class TestDateRange(unittest.TestCase):
    """DateRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateRange:
        """Test DateRange
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateRange`
        """
        model = DateRange()  # noqa: E501
        if include_optional:
            return DateRange(
                lower = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                upper = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                lower_bound_type = 'CLOSED',
                upper_bound_type = 'CLOSED'
            )
        else:
            return DateRange(
        )
        """

    def testDateRange(self):
        """Test DateRange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
