# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.score_state import ScoreState  # noqa: E501

class TestScoreState(unittest.TestCase):
    """ScoreState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScoreState(self):
        """Test ScoreState"""
        # inst = ScoreState()

if __name__ == '__main__':
    unittest.main()
