# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.date_time_tz_range import DateTimeTzRange  # noqa: E501

class TestDateTimeTzRange(unittest.TestCase):
    """DateTimeTzRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateTimeTzRange:
        """Test DateTimeTzRange
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateTimeTzRange`
        """
        model = DateTimeTzRange()  # noqa: E501
        if include_optional:
            return DateTimeTzRange(
                lower = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                upper = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                lower_bound_type = 'CLOSED',
                upper_bound_type = 'CLOSED'
            )
        else:
            return DateTimeTzRange(
        )
        """

    def testDateTimeTzRange(self):
        """Test DateTimeTzRange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
