# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.activity_state import ActivityState  # noqa: E501

class TestActivityState(unittest.TestCase):
    """ActivityState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityState(self):
        """Test ActivityState"""
        # inst = ActivityState()

if __name__ == '__main__':
    unittest.main()
