# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.models_api_v2_recoveries_responses_mdas_recovery import ModelsApiV2RecoveriesResponsesMDASRecovery  # noqa: E501

class TestModelsApiV2RecoveriesResponsesMDASRecovery(unittest.TestCase):
    """ModelsApiV2RecoveriesResponsesMDASRecovery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsApiV2RecoveriesResponsesMDASRecovery:
        """Test ModelsApiV2RecoveriesResponsesMDASRecovery
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsApiV2RecoveriesResponsesMDASRecovery`
        """
        model = ModelsApiV2RecoveriesResponsesMDASRecovery()  # noqa: E501
        if include_optional:
            return ModelsApiV2RecoveriesResponsesMDASRecovery(
                recovery_id = '',
                user_id = 56,
                version = 56,
                cycle_id = 56,
                type = '',
                start_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                score = 56,
                is_normal = True,
                quality_duration = 56,
                latency = 56,
                is_significant = True,
                debt_pre = 1.337,
                debt_post = 1.337,
                need_from_strain = 1.337,
                sleep_need = 1.337,
                habitual_sleep_need = 1.337,
                disturbances = 56,
                time_in_bed = 1.337,
                light_sleep_duration = 56,
                slow_wave_sleep_duration = 56,
                rem_sleep_duration = 56,
                cycles_count = 56,
                wake_duration = 56,
                arousal_time = 1.337,
                no_data_duration = 56,
                in_sleep_efficiency = 1.337,
                credit_from_naps = 1.337,
                respiratory_rate = 1.337,
                skin_temp_celsius = 1.337,
                history_size = 1.337,
                spo2 = 1.337,
                algo_version = '',
                projected_score = 1.337,
                projected_sleep = 1.337,
                sleep_consistency = 1.337,
                total_wake_events = 56,
                optimal_sleep_time_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                optimal_sleep_time_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                recovery_score = 56,
                resting_heart_rate = 56,
                hrv_rmssd = 1.337,
                is_calibrating = True,
                rhr_component = 1.337,
                hrv_component = 1.337,
                recovery_rate = 1.337,
                hr_baseline = 1.337,
                score_state = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ModelsApiV2RecoveriesResponsesMDASRecovery(
                recovery_id = '',
                user_id = 56,
                start_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                score = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testModelsApiV2RecoveriesResponsesMDASRecovery(self):
        """Test ModelsApiV2RecoveriesResponsesMDASRecovery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
