# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.activities_api import ActivitiesApi  # noqa: E501


class TestActivitiesApi(unittest.TestCase):
    """ActivitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivitiesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_batch_create_activities_data_sci_mdas_v1_activities_batch_post(self) -> None:
        """Test case for batch_create_activities_data_sci_mdas_v1_activities_batch_post

        Batch Create Activities  # noqa: E501
        """
        pass

    def test_create_activity_data_sci_mdas_v1_activities_post(self) -> None:
        """Test case for create_activity_data_sci_mdas_v1_activities_post

        Create Activity  # noqa: E501
        """
        pass

    def test_create_activity_data_sci_mdas_v2_activities_post(self) -> None:
        """Test case for create_activity_data_sci_mdas_v2_activities_post

        Create Activity  # noqa: E501
        """
        pass

    def test_delete_activity_data_sci_mdas_v1_activities_activity_id_delete(self) -> None:
        """Test case for delete_activity_data_sci_mdas_v1_activities_activity_id_delete

        Delete Activity  # noqa: E501
        """
        pass

    def test_delete_activity_data_sci_mdas_v2_activities_activity_id_delete(self) -> None:
        """Test case for delete_activity_data_sci_mdas_v2_activities_activity_id_delete

        Delete Activity  # noqa: E501
        """
        pass

    def test_get_activities_in_range_for_user_data_sci_mdas_v1_activities_get(self) -> None:
        """Test case for get_activities_in_range_for_user_data_sci_mdas_v1_activities_get

        Get Activities In Range For User  # noqa: E501
        """
        pass

    def test_get_activities_in_range_for_user_data_sci_mdas_v2_activities_get(self) -> None:
        """Test case for get_activities_in_range_for_user_data_sci_mdas_v2_activities_get

        Get Activities In Range For User  # noqa: E501
        """
        pass

    def test_update_activity_data_sci_mdas_v1_activities_activity_id_put(self) -> None:
        """Test case for update_activity_data_sci_mdas_v1_activities_activity_id_put

        Update Activity  # noqa: E501
        """
        pass

    def test_update_activity_data_sci_mdas_v2_activities_activity_id_put(self) -> None:
        """Test case for update_activity_data_sci_mdas_v2_activities_activity_id_put

        Update Activity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
