# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.models_api_v2_activities_responses_mdas_activity import ModelsApiV2ActivitiesResponsesMDASActivity  # noqa: E501

class TestModelsApiV2ActivitiesResponsesMDASActivity(unittest.TestCase):
    """ModelsApiV2ActivitiesResponsesMDASActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsApiV2ActivitiesResponsesMDASActivity:
        """Test ModelsApiV2ActivitiesResponsesMDASActivity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsApiV2ActivitiesResponsesMDASActivity`
        """
        model = ModelsApiV2ActivitiesResponsesMDASActivity()  # noqa: E501
        if include_optional:
            return ModelsApiV2ActivitiesResponsesMDASActivity(
                activity_id = '',
                user_id = 56,
                start_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timezone = '',
                timezone_offset = '',
                source = 'auto',
                score_state = 'pending',
                score_type = 'RECOVERY',
                type = '',
                source_id = '',
                version = 56,
                cycle_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ModelsApiV2ActivitiesResponsesMDASActivity(
                activity_id = '',
                user_id = 56,
                start_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = 'auto',
                score_state = 'pending',
                score_type = 'RECOVERY',
                type = '',
                version = 56,
                cycle_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testModelsApiV2ActivitiesResponsesMDASActivity(self):
        """Test ModelsApiV2ActivitiesResponsesMDASActivity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
