# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ActivitySource(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    USER = 'user'
    TEAM = 'team'
    AUTO_PLUS_USER = 'auto+user'
    EXTERNAL = 'external'

    @classmethod
    def from_json(cls, json_str: str) -> ActivitySource:
        """Create an instance of ActivitySource from a JSON string"""
        return ActivitySource(json.loads(json_str))


