# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapi_client.models.activity_source import ActivitySource
from openapi_client.models.score_state import ScoreState
from openapi_client.models.score_type import ScoreType

class ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest(BaseModel):
    """
    Base class for MDA activities request.  # noqa: E501
    """
    user_id: StrictInt = Field(...)
    start_timestamp: datetime = Field(...)
    end_timestamp: datetime = Field(...)
    timezone: Optional[StrictStr] = None
    timezone_offset: Optional[StrictStr] = None
    source: ActivitySource = Field(...)
    score_state: ScoreState = Field(...)
    type: StrictStr = Field(...)
    score_type: ScoreType = Field(...)
    source_id: Optional[StrictStr] = None
    version: StrictInt = Field(...)
    cycle_id: StrictInt = Field(...)
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)
    __properties = ["user_id", "start_timestamp", "end_timestamp", "timezone", "timezone_offset", "source", "score_state", "type", "score_type", "source_id", "version", "cycle_id", "created_at", "updated_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest:
        """Create an instance of ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest:
        """Create an instance of ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest.parse_obj(obj)

        _obj = ModelsApiV2ActivitiesRequestsUpdateMDASActivityRequest.parse_obj({
            "user_id": obj.get("user_id"),
            "start_timestamp": obj.get("start_timestamp"),
            "end_timestamp": obj.get("end_timestamp"),
            "timezone": obj.get("timezone"),
            "timezone_offset": obj.get("timezone_offset"),
            "source": obj.get("source"),
            "score_state": obj.get("score_state"),
            "type": obj.get("type"),
            "score_type": obj.get("score_type"),
            "source_id": obj.get("source_id"),
            "version": obj.get("version"),
            "cycle_id": obj.get("cycle_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


