# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from openapi_client.models.cycle_state import CycleState

class ModelsApiV2CyclesRequestsUpdateMDASCycleRequest(BaseModel):
    """
    Representation of a cycle in the MDAS database. Based on https://github.com/WhoopInc/activities-service/blob/4e6bd0353cce859d6923bbb03b53afaf0d075af6/activities-models/src/main/java/com/whoop/activity/model/cycles/CycleIF  # noqa: E501
    """
    user_id: StrictInt = Field(...)
    start_timestamp: datetime = Field(...)
    end_timestamp: Optional[datetime] = None
    sleep_need: Optional[StrictInt] = None
    predicted_end: datetime = Field(...)
    timezone_offset: StrictStr = Field(...)
    start_day: date = Field(...)
    end_day: date = Field(...)
    intensity_score: Optional[Union[StrictFloat, StrictInt]] = None
    data_state: CycleState = Field(...)
    day_strain: Optional[Union[StrictFloat, StrictInt]] = None
    day_kilojoules: Optional[Union[StrictFloat, StrictInt]] = None
    day_avg_heart_rate: Optional[StrictInt] = None
    day_max_heart_rate: Optional[StrictInt] = None
    scaled_strain: Optional[Union[StrictFloat, StrictInt]] = None
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)
    __properties = ["user_id", "start_timestamp", "end_timestamp", "sleep_need", "predicted_end", "timezone_offset", "start_day", "end_day", "intensity_score", "data_state", "day_strain", "day_kilojoules", "day_avg_heart_rate", "day_max_heart_rate", "scaled_strain", "created_at", "updated_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModelsApiV2CyclesRequestsUpdateMDASCycleRequest:
        """Create an instance of ModelsApiV2CyclesRequestsUpdateMDASCycleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModelsApiV2CyclesRequestsUpdateMDASCycleRequest:
        """Create an instance of ModelsApiV2CyclesRequestsUpdateMDASCycleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModelsApiV2CyclesRequestsUpdateMDASCycleRequest.parse_obj(obj)

        _obj = ModelsApiV2CyclesRequestsUpdateMDASCycleRequest.parse_obj({
            "user_id": obj.get("user_id"),
            "start_timestamp": obj.get("start_timestamp"),
            "end_timestamp": obj.get("end_timestamp"),
            "sleep_need": obj.get("sleep_need"),
            "predicted_end": obj.get("predicted_end"),
            "timezone_offset": obj.get("timezone_offset"),
            "start_day": obj.get("start_day"),
            "end_day": obj.get("end_day"),
            "intensity_score": obj.get("intensity_score"),
            "data_state": obj.get("data_state"),
            "day_strain": obj.get("day_strain"),
            "day_kilojoules": obj.get("day_kilojoules"),
            "day_avg_heart_rate": obj.get("day_avg_heart_rate"),
            "day_max_heart_rate": obj.get("day_max_heart_rate"),
            "scaled_strain": obj.get("scaled_strain"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


