# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr

class ModelsApiV2RecoveriesResponsesMDASRecovery(BaseModel):
    """
    All models should inherit from this. If they have special serialization concerns, they can override Config.  >>> class FunTime(WhoopModel): ...     name: str ...     start_time: datetime.datetime ... >>> d = { ... \"name\": \"yay\", ... \"start_time\": datetime.datetime(2020, 1, 1, hour=0, tzinfo=datetime.timezone.utc), ... \"extraBadField\": 3 ... } >>> FunTime(**d).json() '{\"name\": \"yay\", \"start_time\": \"2020-01-01T00:00:00.000+00:00\"}'  # noqa: E501
    """
    recovery_id: StrictStr = Field(...)
    user_id: StrictInt = Field(...)
    version: Optional[StrictInt] = None
    cycle_id: Optional[StrictInt] = None
    type: Optional[StrictStr] = None
    start_timestamp: datetime = Field(...)
    end_timestamp: datetime = Field(...)
    score: StrictInt = Field(...)
    is_normal: Optional[StrictBool] = None
    quality_duration: Optional[StrictInt] = None
    latency: Optional[StrictInt] = None
    is_significant: Optional[StrictBool] = None
    debt_pre: Optional[Union[StrictFloat, StrictInt]] = None
    debt_post: Optional[Union[StrictFloat, StrictInt]] = None
    need_from_strain: Optional[Union[StrictFloat, StrictInt]] = None
    sleep_need: Optional[Union[StrictFloat, StrictInt]] = None
    habitual_sleep_need: Optional[Union[StrictFloat, StrictInt]] = None
    disturbances: Optional[StrictInt] = None
    time_in_bed: Optional[Union[StrictFloat, StrictInt]] = None
    light_sleep_duration: Optional[StrictInt] = None
    slow_wave_sleep_duration: Optional[StrictInt] = None
    rem_sleep_duration: Optional[StrictInt] = None
    cycles_count: Optional[StrictInt] = None
    wake_duration: Optional[StrictInt] = None
    arousal_time: Optional[Union[StrictFloat, StrictInt]] = None
    no_data_duration: Optional[StrictInt] = None
    in_sleep_efficiency: Optional[Union[StrictFloat, StrictInt]] = None
    credit_from_naps: Optional[Union[StrictFloat, StrictInt]] = None
    respiratory_rate: Optional[Union[StrictFloat, StrictInt]] = None
    skin_temp_celsius: Optional[Union[StrictFloat, StrictInt]] = None
    history_size: Optional[Union[StrictFloat, StrictInt]] = None
    spo2: Optional[Union[StrictFloat, StrictInt]] = None
    algo_version: Optional[StrictStr] = None
    projected_score: Optional[Union[StrictFloat, StrictInt]] = None
    projected_sleep: Optional[Union[StrictFloat, StrictInt]] = None
    sleep_consistency: Optional[Union[StrictFloat, StrictInt]] = None
    total_wake_events: Optional[StrictInt] = None
    optimal_sleep_time_start: Optional[datetime] = None
    optimal_sleep_time_end: Optional[datetime] = None
    recovery_score: Optional[StrictInt] = None
    resting_heart_rate: Optional[StrictInt] = None
    hrv_rmssd: Optional[Union[StrictFloat, StrictInt]] = None
    is_calibrating: Optional[StrictBool] = None
    rhr_component: Optional[Union[StrictFloat, StrictInt]] = None
    hrv_component: Optional[Union[StrictFloat, StrictInt]] = None
    recovery_rate: Optional[Union[StrictFloat, StrictInt]] = None
    hr_baseline: Optional[Union[StrictFloat, StrictInt]] = None
    score_state: Optional[StrictStr] = None
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)
    __properties = ["recovery_id", "user_id", "version", "cycle_id", "type", "start_timestamp", "end_timestamp", "score", "is_normal", "quality_duration", "latency", "is_significant", "debt_pre", "debt_post", "need_from_strain", "sleep_need", "habitual_sleep_need", "disturbances", "time_in_bed", "light_sleep_duration", "slow_wave_sleep_duration", "rem_sleep_duration", "cycles_count", "wake_duration", "arousal_time", "no_data_duration", "in_sleep_efficiency", "credit_from_naps", "respiratory_rate", "skin_temp_celsius", "history_size", "spo2", "algo_version", "projected_score", "projected_sleep", "sleep_consistency", "total_wake_events", "optimal_sleep_time_start", "optimal_sleep_time_end", "recovery_score", "resting_heart_rate", "hrv_rmssd", "is_calibrating", "rhr_component", "hrv_component", "recovery_rate", "hr_baseline", "score_state", "created_at", "updated_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ModelsApiV2RecoveriesResponsesMDASRecovery:
        """Create an instance of ModelsApiV2RecoveriesResponsesMDASRecovery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ModelsApiV2RecoveriesResponsesMDASRecovery:
        """Create an instance of ModelsApiV2RecoveriesResponsesMDASRecovery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ModelsApiV2RecoveriesResponsesMDASRecovery.parse_obj(obj)

        _obj = ModelsApiV2RecoveriesResponsesMDASRecovery.parse_obj({
            "recovery_id": obj.get("recovery_id"),
            "user_id": obj.get("user_id"),
            "version": obj.get("version"),
            "cycle_id": obj.get("cycle_id"),
            "type": obj.get("type"),
            "start_timestamp": obj.get("start_timestamp"),
            "end_timestamp": obj.get("end_timestamp"),
            "score": obj.get("score"),
            "is_normal": obj.get("is_normal"),
            "quality_duration": obj.get("quality_duration"),
            "latency": obj.get("latency"),
            "is_significant": obj.get("is_significant"),
            "debt_pre": obj.get("debt_pre"),
            "debt_post": obj.get("debt_post"),
            "need_from_strain": obj.get("need_from_strain"),
            "sleep_need": obj.get("sleep_need"),
            "habitual_sleep_need": obj.get("habitual_sleep_need"),
            "disturbances": obj.get("disturbances"),
            "time_in_bed": obj.get("time_in_bed"),
            "light_sleep_duration": obj.get("light_sleep_duration"),
            "slow_wave_sleep_duration": obj.get("slow_wave_sleep_duration"),
            "rem_sleep_duration": obj.get("rem_sleep_duration"),
            "cycles_count": obj.get("cycles_count"),
            "wake_duration": obj.get("wake_duration"),
            "arousal_time": obj.get("arousal_time"),
            "no_data_duration": obj.get("no_data_duration"),
            "in_sleep_efficiency": obj.get("in_sleep_efficiency"),
            "credit_from_naps": obj.get("credit_from_naps"),
            "respiratory_rate": obj.get("respiratory_rate"),
            "skin_temp_celsius": obj.get("skin_temp_celsius"),
            "history_size": obj.get("history_size"),
            "spo2": obj.get("spo2"),
            "algo_version": obj.get("algo_version"),
            "projected_score": obj.get("projected_score"),
            "projected_sleep": obj.get("projected_sleep"),
            "sleep_consistency": obj.get("sleep_consistency"),
            "total_wake_events": obj.get("total_wake_events"),
            "optimal_sleep_time_start": obj.get("optimal_sleep_time_start"),
            "optimal_sleep_time_end": obj.get("optimal_sleep_time_end"),
            "recovery_score": obj.get("recovery_score"),
            "resting_heart_rate": obj.get("resting_heart_rate"),
            "hrv_rmssd": obj.get("hrv_rmssd"),
            "is_calibrating": obj.get("is_calibrating"),
            "rhr_component": obj.get("rhr_component"),
            "hrv_component": obj.get("hrv_component"),
            "recovery_rate": obj.get("recovery_rate"),
            "hr_baseline": obj.get("hr_baseline"),
            "score_state": obj.get("score_state"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


