# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ScoreType(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    RECOVERY = 'RECOVERY'
    WEIGHTLIFTING_MSK = 'WEIGHTLIFTING_MSK'
    CARDIO = 'CARDIO'
    SLEEP = 'SLEEP'

    @classmethod
    def from_json(cls, json_str: str) -> ScoreType:
        """Create an instance of ScoreType from a JSON string"""
        return ScoreType(json.loads(json_str))


