# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

from typing import List

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from whoopcommons.model.whoop_model import WhoopModel

from data_sci_mdas.models.models_api_v1_activities_requests_create_mdas_activity_request import (
    ModelsApiV1ActivitiesRequestsCreateMDASActivityRequest,
)


class BatchCreateMDASActivitiesRequest(WhoopModel):
    """
    All models should inherit from this. If they have special serialization concerns, they can override Config.  >>> class FunTime(WhoopModel): ...     name: str ...     start_time: datetime.datetime ... >>> d = { ... \"name\": \"yay\", ... \"start_time\": datetime.datetime(2020, 1, 1, hour=0, tzinfo=datetime.timezone.utc), ... \"extraBadField\": 3 ... } >>> FunTime(**d).json() '{\"name\": \"yay\", \"start_time\": \"2020-01-01T00:00:00.000+00:00\"}'  # noqa: E501
    """

    activities: conlist(ModelsApiV1ActivitiesRequestsCreateMDASActivityRequest) = Field(...)
