# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from aenum import Enum


class BoundType(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    CLOSED = "CLOSED"
    OPEN = "OPEN"
