# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from whoopcommons.model.whoop_model import WhoopModel

from data_sci_mdas.models.bound_type import BoundType


class DateTimeTzRange(WhoopModel):
    """
    This exists and is weird because we have APIs that return ranges as semantic strings, which work with Postgres range types.  For instance, the `during` field in the cycle model is given as  \"['2020-08-17T03:42:01.160Z','2020-08-17T12:16:29.582Z')\"  This model makes it so that you can deserialize fields of this type from those strings. When this class is serialized, the strings will be the same.  I would made this Generic, but Pydantic doesn't work with Generics + Python < 3.7, so this base class has upper and lower bounds of type `Any`. Subclasses can override the `upper` and `lower` fields with more specific types, but the elements will be deserialized using the WhoopModel.Config by default.  # noqa: E501
    """

    lower: Optional[datetime] = None
    upper: Optional[datetime] = None
    lower_bound_type: Optional[BoundType] = None
    upper_bound_type: Optional[BoundType] = None
