# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

from datetime import datetime
from typing import Optional, Union

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from whoopcommons.model.whoop_model import WhoopModel

from data_sci_mdas.models.cycle_state import CycleState
from data_sci_mdas.models.date_range import DateRange
from data_sci_mdas.models.date_time_tz_range import DateTimeTzRange


class ModelsApiV1CyclesRequestsUpdateMDASCycleRequest(WhoopModel):
    """
    All models should inherit from this. If they have special serialization concerns, they can override Config.  >>> class FunTime(WhoopModel): ...     name: str ...     start_time: datetime.datetime ... >>> d = { ... \"name\": \"yay\", ... \"start_time\": datetime.datetime(2020, 1, 1, hour=0, tzinfo=datetime.timezone.utc), ... \"extraBadField\": 3 ... } >>> FunTime(**d).json() '{\"name\": \"yay\", \"start_time\": \"2020-01-01T00:00:00.000+00:00\"}'  # noqa: E501
    """

    scaled_strain: Optional[Union[StrictFloat, StrictInt]] = None
    during: DateTimeTzRange = Field(...)
    predicted_end: Optional[datetime] = None
    timezone_offset: StrictStr = Field(...)
    days: DateRange = Field(...)
    data_state: CycleState = Field(...)
    day_strain: Optional[Union[StrictFloat, StrictInt]] = None
    day_kilojoules: Optional[Union[StrictFloat, StrictInt]] = None
    day_avg_heart_rate: Optional[StrictInt] = None
    day_max_heart_rate: Optional[StrictInt] = None
    user_id: StrictInt = Field(...)
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)
