# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

from datetime import date, datetime
from typing import Optional, Union

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from whoopcommons.model.whoop_model import WhoopModel

from data_sci_mdas.models.cycle_state import CycleState


class ModelsApiV2CyclesResponsesMDASCycle(WhoopModel):
    """
    Data model representing a cycle returned from MDAS APIs  # noqa: E501
    """

    cycle_id: StrictInt = Field(...)
    user_id: StrictInt = Field(...)
    start_timestamp: datetime = Field(...)
    end_timestamp: Optional[datetime] = None
    sleep_need: Optional[StrictInt] = None
    predicted_end: datetime = Field(...)
    timezone_offset: StrictStr = Field(...)
    start_day: date = Field(...)
    end_day: date = Field(...)
    intensity_score: Optional[Union[StrictFloat, StrictInt]] = None
    data_state: CycleState = Field(...)
    day_strain: Optional[Union[StrictFloat, StrictInt]] = None
    day_kilojoules: Optional[Union[StrictFloat, StrictInt]] = None
    day_avg_heart_rate: Optional[StrictInt] = None
    day_max_heart_rate: Optional[StrictInt] = None
    scaled_strain: Optional[Union[StrictFloat, StrictInt]] = None
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)
