# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from whoopcommons.model.whoop_model import WhoopModel

from data_sci_mdas.models.activity_source import ActivitySource
from data_sci_mdas.models.score_state import ScoreState
from data_sci_mdas.models.score_type import ScoreType


class ModelsApiV2ActivitiesResponsesMDASActivity(WhoopModel):
    """
    All models should inherit from this. If they have special serialization concerns, they can override Config.  >>> class FunTime(WhoopModel): ...     name: str ...     start_time: datetime.datetime ... >>> d = { ... \"name\": \"yay\", ... \"start_time\": datetime.datetime(2020, 1, 1, hour=0, tzinfo=datetime.timezone.utc), ... \"extraBadField\": 3 ... } >>> FunTime(**d).json() '{\"name\": \"yay\", \"start_time\": \"2020-01-01T00:00:00.000+00:00\"}'  # noqa: E501
    """

    activity_id: StrictStr = Field(...)
    user_id: StrictInt = Field(...)
    start_timestamp: datetime = Field(...)
    end_timestamp: datetime = Field(...)
    timezone: Optional[StrictStr] = None
    timezone_offset: Optional[StrictStr] = None
    source: ActivitySource = Field(...)
    score_state: ScoreState = Field(...)
    score_type: ScoreType = Field(...)
    type: StrictStr = Field(...)
    source_id: Optional[StrictStr] = None
    version: StrictInt = Field(...)
    cycle_id: StrictInt = Field(...)
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)
